# Project information
site_name: TIBCO LABS™ Augmented-Reality
site_description: 'Connect Enterprise Data and take actions is everything in future Augmented Reality Implementations.'
site_author: 'TIBCO Software'
site_url: 'https://github.com/TIBCOSoftware/Augmented-Reality'
edit_uri: ''

# Repository
repo_name: 'TIBCOSoftware/Augmented-Reality'
repo_url: 'https://github.com/TIBCOSoftware/Augmented-Reality'

# Configuration
theme:
  name: null
  custom_dir: 'theme/tibco-material'
  logo: 'assets/images/ic-labs.svg'
    #icon: 'cloud'
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false
  favicon: 'assets/images/favicon.ico'

# Navigation
nav:
  - Home: index.md
  - Getting Started: Getting-Started.md
  - Unity3D Packages:
    - Logos: Logos.md
    - Cloud Messaging Basic: eFTL-Basic.md
    #- Cloud Messaging Adv: eFTL-Adv.md
    #- Rendezvous: Rendezvous-Basic.md

# Customization
extra:
  #manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/TIBCOSoftware'
    - type: 'twitter'
      link: 'https://twitter.com/tibco'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/tibco'

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
#markdown_extensions:
#  - admonition
#  - codehilite:
#      guess_lang: false
#  - toc:
#      permalink: true

# Copyright
copyright: 'Copyright &copy; 2020 TIBCO Software Inc. All Rights Reserved.'